package com.youngLogin.model;

public enum InterfaceName {
    LOGIN,VALIDATEPHONE,DAILYMISSIONBAR,REGISTER,SENDSMSCODEFORCLIENT,SENDSMSCODEFORFORGET,
    VALIDATESMSCODE,SETCPASSWORD,VERIFYCPASSWORD,SETPASSWORD,RESETPASSWORD,CAPTCHAFORCLIENT,
    VALIDATECAPTCHAFORCLIENT,FRESHTOKEN,LOGOUT,INVALIDUSER,PHONELOGIN,SMSLOGIN,SMSLOGINFORPIC,
    STARTREGISTER,FINISHREGISTER,CAPTCHA,LOGINGG,WECHATLOGIN
}
